unclassified:
  templateGlobalConfig:
    tier:
      configurationProvider: "null"
      librarySources:
        - libraryProvider:
            scm:
              baseDir: "jenkinsfile-runner/demo/libraries"
              scm:
                git:
                  branches:
                    - name: "*/master"
                  buildChooser: "default"
                  doGenerateSubmoduleConfigurations: false
                  userRemoteConfigs:
                    - credentialsId: "null"
                      url: "file:///repo"